/**
 * AbiliFit - AI-Powered Fitness & Coach Finder Platform
 * Copyright (c) 2026 George Papasotiriou. All rights reserved.
 *
 * SQL Thinking Panel — collapsible side-panel that streams the SQL query
 * being generated by the AI in real-time. Inspired by Aperture's
 * AIThinkingPanel, adapted for AbiliFit's glass aesthetic.
 */

import { AnimatePresence, motion } from 'framer-motion'
import { ChevronRight, Code2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useThemeStore } from '../../store/themeStore'

export interface SQLPanelState {
  sql: string | null
  status: 'idle' | 'thinking' | 'rendering' | 'done'
  latencyMs?: number
  retries?: number
}

interface Props {
  panel: SQLPanelState
}

const CHAR_INTERVAL_MS = 12

export function SQLThinkingPanel({ panel }: Props) {
  const [open, setOpen] = useState(false)
  const [streamed, setStreamed] = useState('')
  const theme = useThemeStore((s) => s.theme)
  const isDark = theme === 'dark'

  const cardBorder = isDark ? 'border-white/10' : 'border-black/10'
  const textMuted = isDark ? 'text-white/60' : 'text-black/55'
  const textBody = isDark ? 'text-white' : 'text-black'
  const chipBg = isDark ? 'bg-white/[0.06]' : 'bg-black/[0.04]'
  const panelBg = isDark ? 'bg-[rgba(10,10,11,0.92)]' : 'bg-[rgba(243,244,248,0.95)]'

  // Auto-open when a query starts
  useEffect(() => {
    if (panel.status === 'thinking' || panel.status === 'rendering') {
      setOpen(true)
    }
  }, [panel.status])

  // Stream SQL character by character
  useEffect(() => {
    if (!panel.sql) {
      setStreamed('')
      return
    }
    setStreamed('')
    let i = 0
    const id = window.setInterval(() => {
      i += 1
      setStreamed(panel.sql!.slice(0, i))
      if (i >= panel.sql!.length) {
        window.clearInterval(id)
      }
    }, CHAR_INTERVAL_MS)
    return () => window.clearInterval(id)
  }, [panel.sql])

  return (
    <>
      {/* Toggle button */}
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className={`fixed top-20 right-4 z-[55] hidden md:flex h-10 items-center gap-2 rounded-full px-3 font-mono text-xs transition-colors hover:opacity-90 ${textMuted} border ${cardBorder} ${chipBg} backdrop-blur-xl`}
        aria-expanded={open}
      >
        <Code2 size={14} />
        <span>SQL</span>
        {panel.status !== 'idle' && (
          <span className="ml-1 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-accent-purple" />
        )}
        <ChevronRight
          size={12}
          className={`transition-transform ${open ? 'rotate-90' : ''}`}
        />
      </button>

      {/* Side panel */}
      <AnimatePresence>
        {open && (
          <motion.aside
            initial={{ x: '100%', opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: '100%', opacity: 0 }}
            transition={{ duration: 0.3, ease: 'easeOut' }}
            className={`fixed top-0 right-0 z-[54] h-full w-[90vw] max-w-md overflow-y-auto p-6 pt-24 border-l ${cardBorder} ${panelBg} backdrop-blur-2xl`}
          >
            <div className={`mb-2 font-mono text-[11px] tracking-wider uppercase ${textMuted}`}>
              SQL Query
            </div>

            {/* Status indicator */}
            <div className="mb-3 h-5 overflow-hidden">
              <AnimatePresence mode="wait">
                <motion.span
                  key={panel.status}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -6 }}
                  transition={{ duration: 0.22 }}
                  className={`inline-flex items-center gap-2 font-mono text-[11px] ${textMuted}`}
                >
                  {panel.status === 'idle' && '// awaiting query'}
                  {panel.status === 'thinking' && (
                    <>
                      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-accent-purple" />
                      thinking…
                    </>
                  )}
                  {panel.status === 'rendering' && (
                    <>
                      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-accent-teal" />
                      generating SQL…
                    </>
                  )}
                  {panel.status === 'done' && (
                    <>
                      <span className="h-1.5 w-1.5 rounded-full bg-green-500" />
                      done
                    </>
                  )}
                </motion.span>
              </AnimatePresence>
            </div>

            {/* SQL code block */}
            <pre className={`font-mono text-xs leading-relaxed whitespace-pre-wrap break-words ${textBody}`}>
              {streamed ||
                (panel.status === 'idle'
                  ? '// awaiting query...'
                  : '// generating...')}
              {panel.sql && streamed.length < panel.sql.length && (
                <span className="animate-pulse">▍</span>
              )}
            </pre>

            {/* Latency & retries */}
            {(panel.latencyMs !== undefined || (panel.retries !== undefined && panel.retries > 0)) &&
              panel.status === 'done' && (
                <div className={`mt-6 space-y-1 border-t pt-4 font-mono text-[11px] ${textMuted} ${cardBorder}`}>
                  {panel.latencyMs !== undefined && <div>latency: {panel.latencyMs}ms</div>}
                  {panel.retries !== undefined && panel.retries > 0 && (
                    <div>retries: {panel.retries}</div>
                  )}
                </div>
              )}
          </motion.aside>
        )}
      </AnimatePresence>
    </>
  )
}
