"""Editorial generation pipeline.

Extracted from /api/editorial so both the HTTP route and the voice
`generate_editorial` tool can share one path: gather charts from the
conversation store → call the editorial LLM → stamp colophon → build
EditorialResponse. Status is part of the return value so callers can
distinguish "ok" from "needs_more_charts" without raising HTTPException.
"""

from __future__ import annotations

import re
import time
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, Literal

from app.conversation import store
from app.llm.anthropic_client import call_editorial_llm
from app.logger import get_logger
from app.models import (
    EditorialMetadata,
    EditorialResponse,
    EditorialSection,
)

log = get_logger("services.editorial_pipeline")


def _compute_token_cost(
    input_tokens: int,
    cache_creation: int,
    cache_read: int,
    output_tokens: int,
) -> float:
    """USD cost for Opus 4.7. Same rates as /query."""
    input_rate = 5.0 / 1_000_000
    output_rate = 25.0 / 1_000_000
    cache_read_rate = input_rate * 0.10
    cache_write_rate = input_rate * 1.25
    return round(
        input_tokens * input_rate
        + cache_creation * cache_write_rate
        + cache_read * cache_read_rate
        + output_tokens * output_rate,
        6,
    )


@dataclass
class EditorialGenerationResult:
    """Unified return type for both HTTP and voice paths."""

    status: Literal["ok", "needs_more_charts", "declined", "error"]
    editorial: EditorialResponse | None = None
    chart_count: int = 0
    error: str | None = None
    declined_payload: dict[str, Any] | None = None


async def generate_editorial_for_conversation(
    conversation_id: str,
    *,
    request_id: str | None = None,
) -> EditorialGenerationResult:
    """Generate an editorial briefing for a conversation. Pure function —
    no HTTP-layer side effects (no raise HTTPException). Callers map the
    result.status to their preferred surface (HTTP code, WS message, etc.).
    """
    started = time.perf_counter()
    req_id = request_id or str(uuid.uuid4())

    charts = store.get_charts_for_editorial(conversation_id)

    if len(charts) < 2:
        log.info(
            "Editorial rejected: insufficient charts",
            extra={
                "request_id": req_id,
                "conversation_id": conversation_id,
                "chart_count": len(charts),
            },
        )
        return EditorialGenerationResult(
            status="needs_more_charts",
            chart_count=len(charts),
        )

    user_language = store.get_dominant_language(conversation_id)
    session_started = store.get_session_start(conversation_id)

    context: dict[str, Any] = {
        "charts": charts,
        "user_language": user_language,
        "session_started_at": session_started,
    }

    log.info(
        "Editorial requested",
        extra={
            "request_id": req_id,
            "conversation_id": conversation_id,
            "chart_count": len(charts),
            "user_language": user_language,
        },
    )

    try:
        llm = call_editorial_llm(context, request_id=req_id)
    except Exception as e:
        log.exception(
            "Editorial LLM call failed",
            extra={"request_id": req_id, "conversation_id": conversation_id, "error": repr(e)},
        )
        return EditorialGenerationResult(
            status="error",
            chart_count=len(charts),
            error=str(e),
        )

    # Per system prompt B1: model may return an error variant.
    if "error" in llm.parsed:
        log.warning(
            "Editorial declined by model",
            extra={"request_id": req_id, "reason": llm.parsed.get("error")},
        )
        return EditorialGenerationResult(
            status="declined",
            chart_count=len(charts),
            declined_payload=llm.parsed,
        )

    # Stamp the timestamp into colophon_stamp. If the LLM left a
    # {timestamp} placeholder, substitute it. Otherwise strip any
    # pre-existing YYYY-MM-DD style date the model may have invented
    # (so we don't double-stamp), then append now_iso.
    now_iso = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    raw_colophon = llm.parsed.get("colophon_stamp", "GENERATED BY APERTURE")
    if "{timestamp}" in raw_colophon:
        colophon = raw_colophon.replace("{timestamp}", now_iso)
    else:
        stripped = re.sub(
            r"\s*·?\s*\d{4}-\d{2}-\d{2}(\s+\d{2}:\d{2})?(\s+UTC)?",
            "",
            raw_colophon,
        ).rstrip()
        colophon = f"{stripped} · {now_iso}"

    token_cost = _compute_token_cost(
        llm.input_tokens,
        llm.cache_creation_tokens,
        llm.cache_read_tokens,
        llm.output_tokens,
    )

    sections = [EditorialSection(**s) for s in llm.parsed.get("sections", [])]

    log.info(
        "Editorial completed",
        extra={
            "request_id": req_id,
            "section_count": len(sections),
            "input_tokens": llm.input_tokens,
            "cache_creation_tokens": llm.cache_creation_tokens,
            "cache_read_tokens": llm.cache_read_tokens,
            "output_tokens": llm.output_tokens,
            "token_cost_usd": token_cost,
            "latency_ms": int((time.perf_counter() - started) * 1000),
        },
    )

    editorial = EditorialResponse(
        title=llm.parsed["title"],
        dek=llm.parsed["dek"],
        kicker=llm.parsed["kicker"],
        sections=sections,
        methodology_note=llm.parsed["methodology_note"],
        colophon_stamp=colophon,
        metadata=EditorialMetadata(
            request_id=req_id,
            conversation_id=conversation_id,
            chart_count=len(charts),
            latency_ms=int((time.perf_counter() - started) * 1000),
            token_cost_usd=token_cost,
            input_tokens=llm.input_tokens,
            cache_creation_tokens=llm.cache_creation_tokens,
            cache_read_tokens=llm.cache_read_tokens,
            output_tokens=llm.output_tokens,
        ),
    )

    return EditorialGenerationResult(
        status="ok",
        editorial=editorial,
        chart_count=len(charts),
    )
